version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3010:3000" # redireciona para outra porta local
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=https://apiwhats.digitnet.com.br
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=whaticket
      - DB_PASS=Maria182512
      - DB_NAME=whaticket
      - JWT_SECRET=chave_super_secreta_qualquer
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONTEND_URL=https://whats.digitnet.com.br
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Maria182512
      - MYSQL_DATABASE=whaticket
      - MYSQL_USER=whaticket
      - MYSQL_PASSWORD=Maria182512
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
